train:
  dirs:
    - /scratch/gpfs/IOJALVO/gnn-tracking/object_condensation/graphs_v6_cut2/part_1
    - /scratch/gpfs/IOJALVO/gnn-tracking/object_condensation/graphs_v6_cut2/part_2
    - /scratch/gpfs/IOJALVO/gnn-tracking/object_condensation/graphs_v6_cut2/part_3
    - /scratch/gpfs/IOJALVO/gnn-tracking/object_condensation/graphs_v6_cut2/part_4
    - /scratch/gpfs/IOJALVO/gnn-tracking/object_condensation/graphs_v6_cut2/part_5
    - /scratch/gpfs/IOJALVO/gnn-tracking/object_condensation/graphs_v6_cut2/part_6
    - /scratch/gpfs/IOJALVO/gnn-tracking/object_condensation/graphs_v6_cut2/part_7
    - /scratch/gpfs/IOJALVO/gnn-tracking/object_condensation/graphs_v6_cut2/part_8
  sample_size: 28800
  batch_size: 4
val:
  dirs:
    - /scratch/gpfs/IOJALVO/gnn-tracking/object_condensation/graphs_v6_cut2/part_9
  stop: 5
cpus: 6
