class_path: gnn_tracking.training.tc.TCModule
init_args:
  model:
    class_path: gnn_tracking.models.track_condensation_networks.PreTrainedECGraphTCN
    init_args:
      ec: null
      node_indim: 22
      edge_indim: 44
      h_dim: 192
      e_dim: 192
      hidden_dim: 192
      h_outdim: 12
      L_hc: 2
      alpha_latent: 0.5
  preproc:
    class_path: gnn_tracking.models.graph_construction.MLGraphConstructionFromChkpt
    init_args:
      ml_chkpt_path: /home/kl5675/Documents/23/git_sync/hyperparameter_optimization2/scripts/pixel/lightning_logs/quokka-of-algebraic-dew/checkpoints/epoch=59-step=54000.ckpt
      max_num_neighbors: 3
      max_radius: 1.
      use_embedding_features: true
      build_edge_features: true
      ml_model_only: false
      ml_freeze: false
  lw_repulsive: 0.74
  lw_background: 0.
  background_loss: null
  potential_loss:
    class_path: gnn_tracking.metrics.losses.PotentialLoss
    init_args:
      q_min: 0.01
      radius_threshold: 1.0
      attr_pt_thld: 0.9
  cluster_scanner:
    class_path: gnn_tracking.postprocessing.dbscanscanner.DBSCANHyperParamScanner
    init_args:
      n_trials:
        class_path: gnn_tracking.postprocessing.clusterscanner.PulsedNTrials
        init_args:
          warmup_epoch: 0
          low_trials: 6
          high_trials: 12
          high_every: 3
      n_jobs: 3
      min_samples_range: [1, 1]
  optimizer:
    class_path: torch.optim.Adam
    init_args:
      lr: 0.0008
  scheduler:
    class_path: torch.optim.lr_scheduler.LinearLR
    init_args:
      start_factor: 1.
      end_factor: 0.1
      total_iters: 18
