class_path: gnn_tracking.training.ec.ECModule
init_args:
  model:
    class_path: gnn_tracking.models.edge_filter.EFMLP
    init_args:
      node_indim: 14
      edge_indim: 4
      hidden_dim: 256
      depth: 5
  loss_fct:
    class_path: gnn_tracking.metrics.losses.HaughtyFocalLoss
    init_args:
      pt_thld: 0.9
      alpha: 0.4
      gamma: 4.0
  optimizer:
    class_path: torch.optim.Adam
    init_args:
      lr: 0.0004
