class_path: gnn_tracking.training.tc.TCModule
init_args:
  model:
    class_path: gnn_tracking.models.track_condensation_networks.PreTrainedECGraphTCN
    init_args:
      ec: null
      node_indim: 22
      edge_indim: 44
      h_dim: 192
      e_dim: 192
      hidden_dim: 192
      h_outdim: 12
      L_hc: 3
  preproc:
    class_path: gnn_tracking.models.graph_construction.MLGraphConstructionFromChkpt
    init_args:
      max_num_neighbors: 15
      max_radius: 1.
      use_embedding_features: true
      build_edge_features: true
      embedding_slice: [0, 8]
  lw_repulsive: 0.74
  lw_background: 0.
  background_loss: null
  potential_loss:
    class_path: gnn_tracking.metrics.losses.PotentialLoss
    init_args:
      q_min: 0.01
      radius_threshold: 1.0
      attr_pt_thld: 0.9
  cluster_scanner:
    class_path: gnn_tracking.postprocessing.dbscanscanner.DBSCANHyperParamScanner
    init_args:
      n_trials:
        class_path: gnn_tracking.postprocessing.clusterscanner.PulsedNTrials
        init_args:
          warmup_epoch: 0
          low_trials: 6
          high_trials: 12
          high_every: 3
      n_jobs: 3
      min_samples_range: [1, 1]
  optimizer:
    class_path: torch.optim.Adam
    init_args:
      lr: 0.0008
