class_path: gnn_tracking.training.tc.TCModule
init_args:
  model:
    class_path: gnn_tracking.models.track_condensation_networks.PreTrainedECGraphTCN
    init_args:
      ec: null
      node_indim: 22
      edge_indim: 44
      h_dim: 192
      e_dim: 192
      hidden_dim: 192
      h_outdim: 24
      L_hc: 5
      alpha_latent: 0.5
      n_embedding_coords: 8
  preproc:
    class_path: gnn_tracking.models.graph_construction.MLGraphConstructionFromChkpt
    init_args:
      ml_chkpt_path: /home/dc3896/devdoot-gnn-tracking-experiments/experiments/lightning_logs/quiet-origami-prawn/checkpoints/epoch=136-n_edges_frac_segment50_95=197442.95.ckpt
      max_num_neighbors: 8
      max_radius: 1.
      use_embedding_features: true
      build_edge_features: true
  lw_repulsive: 0.74
  lw_background: 0.01
  background_loss:
    class_path: gnn_tracking.metrics.losses.BackgroundLoss
    init_args:
      sb: 0.09
  potential_loss:
    class_path: gnn_tracking.metrics.losses.PotentialLoss
    init_args:
      q_min: 0.01
      radius_threshold: 1.0
      attr_pt_thld: 0.9
  cluster_scanner:
    class_path: gnn_tracking.postprocessing.dbscanscanner.DBSCANHyperParamScanner
    init_args:
      n_trials: 60
      n_jobs: 6
      keep_best: 30
  optimizer:
    class_path: torch.optim.Adam
    init_args:
      lr: 0.0008
  scheduler:
    class_path: torch.optim.lr_scheduler.LinearLR
    init_args:
      start_factor: 1.
      end_factor: 0.1
      total_iters: 50
