class_path: gnn_tracking.training.tc.TCModule
init_args:
  model:
    class_path: gnn_tracking.models.track_condensation_networks.GraphTCNForMLGCPipeline
    init_args:
      node_indim: 22
      edge_indim: 44
      h_dim: 192
      e_dim: 192
      hidden_dim: 192
      h_outdim: 24
      L_hc: 5
      alpha_latent: 0.5
      n_embedding_coords: 8
  preproc:
    class_path: gnn_tracking.models.graph_construction.MLGraphConstructionFromChkpt
    init_args:
      ml_chkpt_path: /scratch/gpfs/IOJALVO/gnn-tracking/object_condensation/model_exchange/gc/quiet-origami-prawn_compatible.ckpt
      max_num_neighbors: 10
      max_radius: 1.
      use_embedding_features: true
      build_edge_features: true
  loss_fct:
    class_path: gnn_tracking.metrics.losses.oc.CondensationLossRG
    init_args:
      q_min: 0.01
      pt_thld: 0.9
      lw_repulsive: 0.74
      lw_noise: 0.
      lw_coward: 0.
      max_num_neighbors: 64
  cluster_scanner:
    class_path: gnn_tracking.postprocessing.dbscanscanner.DBSCANHyperParamScanner
    init_args:
      n_trials: 60
      n_jobs: 6
      keep_best: 30
  optimizer:
    class_path: torch.optim.Adam
    init_args:
      lr: 0.0008
  scheduler:
    class_path: torch.optim.lr_scheduler.LinearLR
    init_args:
      start_factor: 1.
      end_factor: 0.1
      total_iters: 50
