class_path: gnn_tracking.training.ml.MLModule
init_args:
  model:
    class_path: gnn_tracking.models.graph_construction.GraphConstructionFCNN
    init_args:
      beta: 0.4
      depth: 6
      hidden_dim: 256
      in_dim: 14
      out_dim: 24
  loss_fct:
    class_path: gnn_tracking.metrics.losses.GraphConstructionHingeEmbeddingLoss
    init_args:
      attr_pt_thld: 0.9
      max_num_neighbors: 256
      p_attr: 2
      p_rep: 2
      r_emb: 1
  lw_repulsive: 0.006
  gc_scanner:
    class_path: gnn_tracking.graph_construction.k_scanner.GraphConstructionKNNScanner
    init_args:
      ks: [7, 8, 9, 10, 11, 12, 13, 14, 15]
  optimizer:
    class_path: torch.optim.Adam
    init_args:
      lr: 0.0007
