class_path: gnn_tracking.training.tc.TCModule
init_args:
  model:
    class_path: gnn_tracking.models.track_condensation_networks.PreTrainedECGraphTCN
    init_args:
      ec: null
      node_indim: 38
      edge_indim: 76
      h_dim: 256
      e_dim: 256
      hidden_dim: 256
      h_outdim: 24
      L_hc: 5
      alpha_latent: 0.5
      n_embedding_coords: 24
  preproc:
    class_path: gnn_tracking.models.graph_construction.MLGraphConstructionFromChkpt
    init_args:
      ml_chkpt_path: /home/kl5675/Documents/23/git_sync/hyperparameter_optimization2/scripts/full_detector/lightning_logs/merciful-reindeer-of-coffee/checkpoints/epoch=79-step=72000.compat.ckpt
      max_num_neighbors: 15
      max_radius: 1.
      use_embedding_features: true
      build_edge_features: true
  lw_repulsive: 5
  lw_background: 0.
  background_loss: null
  potential_loss:
    class_path: gnn_tracking.metrics.losses.PotentialLoss
    init_args:
      q_min: 0.01
      radius_threshold: 1.0
      attr_pt_thld: 0.9
      max_neighbors: 128
  cluster_scanner:
    class_path: gnn_tracking.postprocessing.dbscanscanner.DBSCANHyperParamScanner
    init_args:
      n_trials: 60
      n_jobs: 6
      keep_best: 30
  optimizer:
    class_path: torch.optim.Adam
    init_args:
      lr: 0.0020
  scheduler:
    class_path: torch.optim.lr_scheduler.LinearLR
    init_args:
      start_factor: 1.
      end_factor: 0.1
      total_iters: 18
