class_path: gnn_tracking.training.tc.TCModule
init_args:
  model:
    class_path: gnn_tracking.models.track_condensation_networks.GraphTCNForMLGCPipeline
    init_args:
      node_indim: 38
      edge_indim: 76
      h_dim: 128
      e_dim: 128
      hidden_dim: 128
      h_outdim: 24
      L_hc: 2
      alpha_latent: 0.5
      n_embedding_coords: 24
  preproc:
    class_path: gnn_tracking.models.graph_construction.MLGraphConstructionFromChkpt
    init_args:
      ml_chkpt_path: /home/kl5675/Documents/23/git_sync/hyperparameter_optimization2/scripts/full_detector/lightning_logs/garrulous-peach-manatee/checkpoints/epoch=111-step=50400.compat.ckpt
      max_num_neighbors: 8
      max_radius: 1.
      use_embedding_features: true
      build_edge_features: true
  loss_fct:
    class_path: gnn_tracking.metrics.losses.oc.CondensationLossRG
    init_args:
      q_min: 0.01
      pt_thld: 0.9
      lw_repulsive: 1
      lw_noise: 0.
      lw_coward: 0.
      max_num_neighbors: 32
  cluster_scanner:
    class_path: gnn_tracking.postprocessing.dbscanscanner.DBSCANHyperParamScanner
    init_args:
      n_trials: 60
      n_jobs: 6
      keep_best: 30
  optimizer:
    class_path: torch.optim.Adam
    init_args:
      lr: 0.0007
