class_path: gnn_tracking.training.tc.TCModule
init_args:
  model:
    class_path: gnn_tracking.models.track_condensation_networks.PreTrainedECGraphTCN
    init_args:
      ec: null
      node_indim: 14
      edge_indim: 4
      h_dim: 192
      e_dim: 192
      hidden_dim: 192
      h_outdim: 12
      L_hc: 5
      alpha_hc: 0.4
      feed_edge_weights: true
  lw_repulsive: 0.4
  lw_background: 0.004
  background_loss:
    class_path: gnn_tracking.metrics.losses.BackgroundLoss
    init_args:
      sb: 0.09
  potential_loss:
    class_path: gnn_tracking.metrics.losses.PotentialLoss
    init_args:
      q_min: 0.34
      radius_threshold: 1
      attr_pt_thld: 0.9
  cluster_scanner:
    class_path: gnn_tracking.postprocessing.dbscanscanner.DBSCANHyperParamScanner
    init_args:
      n_trials: 60
      n_jobs: 6
      keep_best: 30
  optimizer:
    class_path: torch.optim.Adam
    init_args:
      lr: 0.0005
  scheduler:
    class_path: torch.optim.lr_scheduler.LinearLR
    init_args:
      start_factor: 1.
      end_factor: 0.05
      total_iters: 20
