class_path: gnn_tracking.training.ml.MLModule
init_args:
  model:
    class_path: gnn_tracking.models.graph_construction.GraphConstructionResIN
    init_args:
      node_indim: 22
      edge_indim: 44
      hidden_dim: 192
      h_outdim: 8
  preproc:
    class_path: gnn_tracking.models.graph_construction.MLGraphConstructionFromChkpt
    init_args:
      ml_chkpt_path: /scratch/gpfs/IOJALVO/gnn-tracking/object_condensation/model_exchange/gc/spiritual-almond-aardwark.ckpt
      max_num_neighbors: 15
      max_radius: 1.
      use_embedding_features: true
      build_edge_features: true
  loss_fct:
    class_path: gnn_tracking.metrics.losses.GraphConstructionHingeEmbeddingLoss
    init_args:
      attr_pt_thld: 0.9
      max_num_neighbors: 256
      p_attr: 2
      p_rep: 2
      r_emb: 1
  lw_repulsive: 0.00195
  gc_scanner:
    class_path: gnn_tracking.graph_construction.k_scanner.GraphConstructionKNNScanner
    init_args:
      ks: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
  optimizer:
    class_path: torch.optim.Adam
    init_args:
      lr: 0.0008
