class_path: gnn_tracking.training.ec.ECModule
init_args:
  model:
    class_path: gnn_tracking.models.edge_filter.EFMLP
    init_args:
      node_indim: 22
      edge_indim: 44
      hidden_dim: 128
      depth: 3
  loss_fct:
    class_path: gnn_tracking.metrics.losses.HaughtyFocalLoss
    init_args:
      pt_thld: 0.9
      alpha: 0.5
      gamma: 1.0
  preproc:
    class_path: gnn_tracking.models.graph_construction.MLGraphConstructionFromChkpt
    init_args:
      ml_chkpt_path: /scratch/gpfs/IOJALVO/gnn-tracking/object_condensation/model_exchange/gc/gc-7dce6aff.ckpt
      max_num_neighbors: 15
      max_radius: 1.
      use_embedding_features: true
      build_edge_features: true
  optimizer:
    class_path: torch.optim.Adam
    init_args:
      lr: 0.0005
