gamma: 1.0
class_path: gnn_tracking.training.ec.ECModule
init_args:
  model:
    class_path: gnn_tracking.models.edge_filter.EFMLP
    init_args:
      node_indim: 22
      edge_indim: 44
      hidden_dim: 128
      depth: 3
  loss_fct:
    class_path: gnn_tracking.metrics.losses.EdgeWeightBCELoss
    init_args:
      pt_thld: 0.9
  preproc:
    class_path: gnn_tracking.models.graph_construction.MLGraphConstructionFromChkpt
    init_args:
      max_num_neighbors: 15
      max_radius: 1.
      use_embedding_features: true
      build_edge_features: true
      embedding_slice: [0, 8]
  optimizer:
    class_path: torch.optim.Adam
    init_args:
      lr: 0.0005
